// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ApplicationStatus.
const (
	Draft     ApplicationStatus = "draft"
	Interview ApplicationStatus = "interview"
	Offer     ApplicationStatus = "offer"
	Rejected  ApplicationStatus = "rejected"
	Sent      ApplicationStatus = "sent"
)

// Valid indicates whether the value is a known member of the ApplicationStatus enum.
func (e ApplicationStatus) Valid() bool {
	switch e {
	case Draft:
		return true
	case Interview:
		return true
	case Offer:
		return true
	case Rejected:
		return true
	case Sent:
		return true
	default:
		return false
	}
}

// Defines values for CollectionRunStatus.
const (
	CollectionRunStatusFailed  CollectionRunStatus = "failed"
	CollectionRunStatusPartial CollectionRunStatus = "partial"
	CollectionRunStatusRunning CollectionRunStatus = "running"
	CollectionRunStatusSuccess CollectionRunStatus = "success"
)

// Valid indicates whether the value is a known member of the CollectionRunStatus enum.
func (e CollectionRunStatus) Valid() bool {
	switch e {
	case CollectionRunStatusFailed:
		return true
	case CollectionRunStatusPartial:
		return true
	case CollectionRunStatusRunning:
		return true
	case CollectionRunStatusSuccess:
		return true
	default:
		return false
	}
}

// Defines values for Grade.
const (
	GradeJunior Grade = "junior"
	GradeMiddle Grade = "middle"
	GradeSenior Grade = "senior"
)

// Valid indicates whether the value is a known member of the Grade enum.
func (e Grade) Valid() bool {
	switch e {
	case GradeJunior:
		return true
	case GradeMiddle:
		return true
	case GradeSenior:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	HealthStatusOk          HealthStatus = "ok"
	HealthStatusUnavailable HealthStatus = "unavailable"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case HealthStatusOk:
		return true
	case HealthStatusUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for LetterVersionAuthor.
const (
	LetterVersionAuthorModel LetterVersionAuthor = "model"
	LetterVersionAuthorUser  LetterVersionAuthor = "user"
)

// Valid indicates whether the value is a known member of the LetterVersionAuthor enum.
func (e LetterVersionAuthor) Valid() bool {
	switch e {
	case LetterVersionAuthorModel:
		return true
	case LetterVersionAuthorUser:
		return true
	default:
		return false
	}
}

// Defines values for PortfolioItemSource.
const (
	Github PortfolioItemSource = "github"
	Manual PortfolioItemSource = "manual"
	Resume PortfolioItemSource = "resume"
)

// Valid indicates whether the value is a known member of the PortfolioItemSource enum.
func (e PortfolioItemSource) Valid() bool {
	switch e {
	case Github:
		return true
	case Manual:
		return true
	case Resume:
		return true
	default:
		return false
	}
}

// Defines values for ProfileTargetGrade.
const (
	ProfileTargetGradeJunior      ProfileTargetGrade = "junior"
	ProfileTargetGradeLessThannil ProfileTargetGrade = "<nil>"
	ProfileTargetGradeMiddle      ProfileTargetGrade = "middle"
	ProfileTargetGradeSenior      ProfileTargetGrade = "senior"
)

// Valid indicates whether the value is a known member of the ProfileTargetGrade enum.
func (e ProfileTargetGrade) Valid() bool {
	switch e {
	case ProfileTargetGradeJunior:
		return true
	case ProfileTargetGradeLessThannil:
		return true
	case ProfileTargetGradeMiddle:
		return true
	case ProfileTargetGradeSenior:
		return true
	default:
		return false
	}
}

// Defines values for ResumeStatus.
const (
	ResumeStatusFailed     ResumeStatus = "failed"
	ResumeStatusNone       ResumeStatus = "none"
	ResumeStatusProcessing ResumeStatus = "processing"
	ResumeStatusReady      ResumeStatus = "ready"
)

// Valid indicates whether the value is a known member of the ResumeStatus enum.
func (e ResumeStatus) Valid() bool {
	switch e {
	case ResumeStatusFailed:
		return true
	case ResumeStatusNone:
		return true
	case ResumeStatusProcessing:
		return true
	case ResumeStatusReady:
		return true
	default:
		return false
	}
}

// Defines values for ScoreExplanationGradeFit.
const (
	Higher  ScoreExplanationGradeFit = "higher"
	Lower   ScoreExplanationGradeFit = "lower"
	Match   ScoreExplanationGradeFit = "match"
	Unknown ScoreExplanationGradeFit = "unknown"
)

// Valid indicates whether the value is a known member of the ScoreExplanationGradeFit enum.
func (e ScoreExplanationGradeFit) Valid() bool {
	switch e {
	case Higher:
		return true
	case Lower:
		return true
	case Match:
		return true
	case Unknown:
		return true
	default:
		return false
	}
}

// Defines values for TokenResponseTokenType.
const (
	Bearer TokenResponseTokenType = "Bearer"
)

// Valid indicates whether the value is a known member of the TokenResponseTokenType enum.
func (e TokenResponseTokenType) Valid() bool {
	switch e {
	case Bearer:
		return true
	default:
		return false
	}
}

// Defines values for Tone.
const (
	Formal   Tone = "formal"
	Friendly Tone = "friendly"
	Neutral  Tone = "neutral"
)

// Valid indicates whether the value is a known member of the Tone enum.
func (e Tone) Valid() bool {
	switch e {
	case Formal:
		return true
	case Friendly:
		return true
	case Neutral:
		return true
	default:
		return false
	}
}

// Defines values for VacancyGrade.
const (
	VacancyGradeJunior      VacancyGrade = "junior"
	VacancyGradeLessThannil VacancyGrade = "<nil>"
	VacancyGradeMiddle      VacancyGrade = "middle"
	VacancyGradeSenior      VacancyGrade = "senior"
)

// Valid indicates whether the value is a known member of the VacancyGrade enum.
func (e VacancyGrade) Valid() bool {
	switch e {
	case VacancyGradeJunior:
		return true
	case VacancyGradeLessThannil:
		return true
	case VacancyGradeMiddle:
		return true
	case VacancyGradeSenior:
		return true
	default:
		return false
	}
}

// Defines values for VacancyWorkFormat.
const (
	VacancyWorkFormatHybrid      VacancyWorkFormat = "hybrid"
	VacancyWorkFormatLessThannil VacancyWorkFormat = "<nil>"
	VacancyWorkFormatOffice      VacancyWorkFormat = "office"
	VacancyWorkFormatRemote      VacancyWorkFormat = "remote"
)

// Valid indicates whether the value is a known member of the VacancyWorkFormat enum.
func (e VacancyWorkFormat) Valid() bool {
	switch e {
	case VacancyWorkFormatHybrid:
		return true
	case VacancyWorkFormatLessThannil:
		return true
	case VacancyWorkFormatOffice:
		return true
	case VacancyWorkFormatRemote:
		return true
	default:
		return false
	}
}

// Defines values for VacancyDetailsGrade.
const (
	VacancyDetailsGradeJunior      VacancyDetailsGrade = "junior"
	VacancyDetailsGradeLessThannil VacancyDetailsGrade = "<nil>"
	VacancyDetailsGradeMiddle      VacancyDetailsGrade = "middle"
	VacancyDetailsGradeSenior      VacancyDetailsGrade = "senior"
)

// Valid indicates whether the value is a known member of the VacancyDetailsGrade enum.
func (e VacancyDetailsGrade) Valid() bool {
	switch e {
	case VacancyDetailsGradeJunior:
		return true
	case VacancyDetailsGradeLessThannil:
		return true
	case VacancyDetailsGradeMiddle:
		return true
	case VacancyDetailsGradeSenior:
		return true
	default:
		return false
	}
}

// Defines values for VacancyDetailsWorkFormat.
const (
	VacancyDetailsWorkFormatHybrid      VacancyDetailsWorkFormat = "hybrid"
	VacancyDetailsWorkFormatLessThannil VacancyDetailsWorkFormat = "<nil>"
	VacancyDetailsWorkFormatOffice      VacancyDetailsWorkFormat = "office"
	VacancyDetailsWorkFormatRemote      VacancyDetailsWorkFormat = "remote"
)

// Valid indicates whether the value is a known member of the VacancyDetailsWorkFormat enum.
func (e VacancyDetailsWorkFormat) Valid() bool {
	switch e {
	case VacancyDetailsWorkFormatHybrid:
		return true
	case VacancyDetailsWorkFormatLessThannil:
		return true
	case VacancyDetailsWorkFormatOffice:
		return true
	case VacancyDetailsWorkFormatRemote:
		return true
	default:
		return false
	}
}

// Defines values for WorkFormat.
const (
	WorkFormatHybrid WorkFormat = "hybrid"
	WorkFormatOffice WorkFormat = "office"
	WorkFormatRemote WorkFormat = "remote"
)

// Valid indicates whether the value is a known member of the WorkFormat enum.
func (e WorkFormat) Valid() bool {
	switch e {
	case WorkFormatHybrid:
		return true
	case WorkFormatOffice:
		return true
	case WorkFormatRemote:
		return true
	default:
		return false
	}
}

// Application defines model for Application.
type Application struct {
	CreatedAt time.Time         `json:"created_at"`
	Id        int64             `json:"id"`
	LetterId  *int64            `json:"letter_id"`
	Status    ApplicationStatus `json:"status"`
	UpdatedAt time.Time         `json:"updated_at"`
	Vacancy   Vacancy           `json:"vacancy"`
}

// ApplicationCreate defines model for ApplicationCreate.
type ApplicationCreate struct {
	VacancyId int64 `json:"vacancy_id"`
}

// ApplicationPage defines model for ApplicationPage.
type ApplicationPage struct {
	Items []Application `json:"items"`
	Total int           `json:"total"`
}

// ApplicationPatch defines model for ApplicationPatch.
type ApplicationPatch struct {
	Status ApplicationStatus `json:"status"`
}

// ApplicationStatus defines model for ApplicationStatus.
type ApplicationStatus string

// CollectionRun defines model for CollectionRun.
type CollectionRun struct {
	Created      int                 `json:"created"`
	ErrorMessage *string             `json:"error_message"`
	Errors       int                 `json:"errors"`
	Fetched      int                 `json:"fetched"`
	FinishedAt   *time.Time          `json:"finished_at"`
	Id           int64               `json:"id"`
	Source       string              `json:"source"`
	StartedAt    time.Time           `json:"started_at"`
	Status       CollectionRunStatus `json:"status"`
	Updated      int                 `json:"updated"`
}

// CollectionRunStatus defines model for CollectionRun.Status.
type CollectionRunStatus string

// CollectionRunPage defines model for CollectionRunPage.
type CollectionRunPage struct {
	Items []CollectionRun `json:"items"`
	Total int             `json:"total"`
}

// DataQuality defines model for DataQuality.
type DataQuality struct {
	BySource []SourceQuality `json:"by_source"`

	// DuplicatesShare Доля склеенных дублей
	DuplicatesShare float64 `json:"duplicates_share"`

	// SalaryShare Доля вакансий с указанной зарплатой
	SalaryShare float64 `json:"salary_share"`

	// SkillsShare Доля вакансий с распознанными навыками
	SkillsShare    float64 `json:"skills_share"`
	TotalVacancies int     `json:"total_vacancies"`
}

// Error defines model for Error.
type Error struct {
	Error struct {
		// Code Машинный код, по нему клиентская часть решает, что делать
		Code string `json:"code"`

		// Message Текст для человека, показывается как есть
		Message string `json:"message"`
	} `json:"error"`
}

// FeedItem defines model for FeedItem.
type FeedItem struct {
	Explanation ScoreExplanation `json:"explanation"`
	Score       float64          `json:"score"`
	Vacancy     Vacancy          `json:"vacancy"`
}

// FeedResponse defines model for FeedResponse.
type FeedResponse struct {
	Items []FeedItem `json:"items"`

	// Simplified `true` — подбор упрощён (без смысловой близости), клиентская часть показывает пометку
	Simplified bool `json:"simplified"`
	Total      int  `json:"total"`
}

// GithubConnectRequest defines model for GithubConnectRequest.
type GithubConnectRequest struct {
	Username string `json:"username"`
}

// Grade defines model for Grade.
type Grade string

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// Letter defines model for Letter.
type Letter struct {
	ApplicationId int64  `json:"application_id"`
	Content       string `json:"content"`
	Id            int64  `json:"id"`

	// Unverified Фрагменты, которых нет в портфолио — подсвечиваются в редакторе
	Unverified []TextFragment `json:"unverified"`
	UpdatedAt  time.Time      `json:"updated_at"`
	VacancyId  int64          `json:"vacancy_id"`
	Version    int            `json:"version"`
}

// LetterCreate defines model for LetterCreate.
type LetterCreate struct {
	// Tone Если не задан — тон из профиля
	Tone *Tone `json:"tone,omitempty"`
}

// LetterPatch defines model for LetterPatch.
type LetterPatch struct {
	Content string `json:"content"`

	// Version Версия, которую правил человек
	Version int `json:"version"`
}

// LetterVersion defines model for LetterVersion.
type LetterVersion struct {
	Author    LetterVersionAuthor `json:"author"`
	Content   string              `json:"content"`
	CreatedAt time.Time           `json:"created_at"`
	Version   int                 `json:"version"`
}

// LetterVersionAuthor defines model for LetterVersion.Author.
type LetterVersionAuthor string

// LetterVersionList defines model for LetterVersionList.
type LetterVersionList struct {
	Items []LetterVersion `json:"items"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// Me defines model for Me.
type Me struct {
	Email    string  `json:"email"`
	FullName string  `json:"full_name"`
	Id       int64   `json:"id"`
	IsAdmin  bool    `json:"is_admin"`
	Profile  Profile `json:"profile"`
}

// PatchMeRequest Все поля необязательны; меняются только переданные.
type PatchMeRequest struct {
	Cities     *[]string `json:"cities,omitempty"`
	FullName   *string   `json:"full_name,omitempty"`
	SalaryFrom *int      `json:"salary_from,omitempty"`

	// SkillIds Полный список навыков профиля (заменяет прежний)
	SkillIds    *[]int64      `json:"skill_ids,omitempty"`
	TargetGrade *Grade        `json:"target_grade,omitempty"`
	TargetTitle *string       `json:"target_title,omitempty"`
	Tone        *Tone         `json:"tone,omitempty"`
	WorkFormats *[]WorkFormat `json:"work_formats,omitempty"`
}

// PortfolioItem defines model for PortfolioItem.
type PortfolioItem struct {
	CreatedAt time.Time           `json:"created_at"`
	Id        int64               `json:"id"`
	Skills    []Skill             `json:"skills"`
	Source    PortfolioItemSource `json:"source"`
	Summary   string              `json:"summary"`
	Title     string              `json:"title"`
	Url       *string             `json:"url"`
}

// PortfolioItemSource defines model for PortfolioItem.Source.
type PortfolioItemSource string

// PortfolioItemCreate defines model for PortfolioItemCreate.
type PortfolioItemCreate struct {
	SkillIds *[]int64 `json:"skill_ids,omitempty"`
	Summary  string   `json:"summary"`
	Title    string   `json:"title"`
	Url      *string  `json:"url,omitempty"`
}

// PortfolioItemList defines model for PortfolioItemList.
type PortfolioItemList struct {
	Items []PortfolioItem `json:"items"`
}

// PortfolioItemPatch defines model for PortfolioItemPatch.
type PortfolioItemPatch struct {
	SkillIds *[]int64 `json:"skill_ids,omitempty"`
	Summary  *string  `json:"summary,omitempty"`
	Title    *string  `json:"title,omitempty"`
	Url      *string  `json:"url,omitempty"`
}

// Profile defines model for Profile.
type Profile struct {
	Cities       []string            `json:"cities"`
	ResumeStatus ResumeStatus        `json:"resume_status"`
	SalaryFrom   *int                `json:"salary_from"`
	Skills       []Skill             `json:"skills"`
	TargetGrade  *ProfileTargetGrade `json:"target_grade"`
	TargetTitle  *string             `json:"target_title"`
	Tone         Tone                `json:"tone"`
	WorkFormats  []WorkFormat        `json:"work_formats"`
}

// ProfileTargetGrade defines model for Profile.TargetGrade.
type ProfileTargetGrade string

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	// Email Почта, регистр не важен
	Email    string `json:"email"`
	FullName string `json:"full_name"`
	Password string `json:"password"`
}

// ResumeStatus defines model for ResumeStatus.
type ResumeStatus string

// ResumeUploadResponse defines model for ResumeUploadResponse.
type ResumeUploadResponse struct {
	ResumeStatus ResumeStatus `json:"resume_status"`
}

// ScoreExplanation defines model for ScoreExplanation.
type ScoreExplanation struct {
	// GradeFit Уровень вакансии относительно желаемого
	GradeFit      ScoreExplanationGradeFit `json:"grade_fit"`
	MatchedSkills []string                 `json:"matched_skills"`
	MissingSkills []string                 `json:"missing_skills"`

	// Parts Четыре части формулы оценки, каждая от 0 до 1
	Parts ScoreParts `json:"parts"`
}

// ScoreExplanationGradeFit Уровень вакансии относительно желаемого
type ScoreExplanationGradeFit string

// ScoreParts Четыре части формулы оценки, каждая от 0 до 1
type ScoreParts struct {
	// Freshness Свежесть вакансии
	Freshness float64 `json:"freshness"`

	// Grade Совпадение уровня
	Grade float64 `json:"grade"`

	// Similarity Смысловая близость; `null` в упрощённой ленте
	Similarity *float64 `json:"similarity"`

	// Skills Покрытие навыков
	Skills float64 `json:"skills"`
}

// Skill defines model for Skill.
type Skill struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}

// SourceQuality defines model for SourceQuality.
type SourceQuality struct {
	LastSuccessAt *time.Time `json:"last_success_at"`
	Source        string     `json:"source"`
	Vacancies     int        `json:"vacancies"`
}

// TextFragment defines model for TextFragment.
type TextFragment struct {
	// End Позиция после последнего символа
	End int `json:"end"`

	// Start Позиция первого символа (в символах, не байтах)
	Start int    `json:"start"`
	Text  string `json:"text"`
}

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	AccessToken string                 `json:"access_token"`
	ExpiresAt   time.Time              `json:"expires_at"`
	TokenType   TokenResponseTokenType `json:"token_type"`
	User        User                   `json:"user"`
}

// TokenResponseTokenType defines model for TokenResponse.TokenType.
type TokenResponseTokenType string

// Tone defines model for Tone.
type Tone string

// User defines model for User.
type User struct {
	Email    string `json:"email"`
	FullName string `json:"full_name"`
	Id       int64  `json:"id"`
	IsAdmin  bool   `json:"is_admin"`
}

// Vacancy defines model for Vacancy.
type Vacancy struct {
	City    *string `json:"city"`
	Company string  `json:"company"`

	// Currency Код ISO 4217: RUB, USD, EUR
	Currency    *string       `json:"currency"`
	Grade       *VacancyGrade `json:"grade"`
	Id          int64         `json:"id"`
	PublishedAt time.Time     `json:"published_at"`

	// SalaryFrom `null` — зарплата не указана. Никогда не `0` и никогда не угадывается
	SalaryFrom *int    `json:"salary_from"`
	SalaryTo   *int    `json:"salary_to"`
	Skills     []Skill `json:"skills"`

	// Source Источник основной копии: headhunter, superjob, ...
	Source string `json:"source"`
	Title  string `json:"title"`

	// Url Ссылка на вакансию у источника
	Url        string             `json:"url"`
	WorkFormat *VacancyWorkFormat `json:"work_format"`
}

// VacancyGrade defines model for Vacancy.Grade.
type VacancyGrade string

// VacancyWorkFormat defines model for Vacancy.WorkFormat.
type VacancyWorkFormat string

// VacancyCopy defines model for VacancyCopy.
type VacancyCopy struct {
	Source string `json:"source"`
	Url    string `json:"url"`
}

// VacancyDetails defines model for VacancyDetails.
type VacancyDetails struct {
	// AlsoOn Та же вакансия у других источников (склеенные дубли)
	AlsoOn  []VacancyCopy `json:"also_on"`
	City    *string       `json:"city"`
	Company string        `json:"company"`

	// Currency Код ISO 4217: RUB, USD, EUR
	Currency    *string              `json:"currency"`
	Description string               `json:"description"`
	Grade       *VacancyDetailsGrade `json:"grade"`
	Id          int64                `json:"id"`
	PublishedAt time.Time            `json:"published_at"`

	// SalaryFrom `null` — зарплата не указана. Никогда не `0` и никогда не угадывается
	SalaryFrom *int    `json:"salary_from"`
	SalaryTo   *int    `json:"salary_to"`
	Skills     []Skill `json:"skills"`

	// Source Источник основной копии: headhunter, superjob, ...
	Source string `json:"source"`
	Title  string `json:"title"`

	// Url Ссылка на вакансию у источника
	Url        string                    `json:"url"`
	WorkFormat *VacancyDetailsWorkFormat `json:"work_format"`
}

// VacancyDetailsGrade defines model for VacancyDetails.Grade.
type VacancyDetailsGrade string

// VacancyDetailsWorkFormat defines model for VacancyDetails.WorkFormat.
type VacancyDetailsWorkFormat string

// VacancyPage defines model for VacancyPage.
type VacancyPage struct {
	Items []Vacancy `json:"items"`
	Total int       `json:"total"`
}

// WorkFormat defines model for WorkFormat.
type WorkFormat string

// Id defines model for Id.
type Id = int64

// Page defines model for Page.
type Page = int

// PerPage defines model for PerPage.
type PerPage = int

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// Unavailable defines model for Unavailable.
type Unavailable = Error

// ValidationError defines model for ValidationError.
type ValidationError = Error

// ListCollectionRunsParams defines parameters for ListCollectionRuns.
type ListCollectionRunsParams struct {
	Source *string `form:"source,omitempty" json:"source,omitempty"`

	// Page Номер страницы, с 1
	Page    *Page    `form:"page,omitempty" json:"page,omitempty"`
	PerPage *PerPage `form:"per_page,omitempty" json:"per_page,omitempty"`
}

// ListApplicationsParams defines parameters for ListApplications.
type ListApplicationsParams struct {
	Status *ApplicationStatus `form:"status,omitempty" json:"status,omitempty"`

	// Page Номер страницы, с 1
	Page    *Page    `form:"page,omitempty" json:"page,omitempty"`
	PerPage *PerPage `form:"per_page,omitempty" json:"per_page,omitempty"`
}

// GetFeedParams defines parameters for GetFeed.
type GetFeedParams struct {
	// City Если не задан — города из профиля
	City *string `form:"city,omitempty" json:"city,omitempty"`

	// Page Номер страницы, с 1
	Page    *Page    `form:"page,omitempty" json:"page,omitempty"`
	PerPage *PerPage `form:"per_page,omitempty" json:"per_page,omitempty"`
}

// UploadResumeMultipartBody defines parameters for UploadResume.
type UploadResumeMultipartBody struct {
	// File PDF или DOCX, не больше 10 МБ
	File openapi_types.File `json:"file"`
}

// SearchSkillsParams defines parameters for SearchSkills.
type SearchSkillsParams struct {
	// Q Начало названия навыка, от 1 символа
	Q     string `form:"q" json:"q"`
	Limit *int   `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListVacanciesParams defines parameters for ListVacancies.
type ListVacanciesParams struct {
	// Q Слова из названия или описания
	Q          *string     `form:"q,omitempty" json:"q,omitempty"`
	City       *string     `form:"city,omitempty" json:"city,omitempty"`
	Grade      *Grade      `form:"grade,omitempty" json:"grade,omitempty"`
	WorkFormat *WorkFormat `form:"work_format,omitempty" json:"work_format,omitempty"`
	SalaryFrom *int        `form:"salary_from,omitempty" json:"salary_from,omitempty"`

	// SkillId Номера навыков; вакансия должна требовать все перечисленные
	SkillId *[]int64 `form:"skill_id,omitempty" json:"skill_id,omitempty"`

	// Page Номер страницы, с 1
	Page    *Page    `form:"page,omitempty" json:"page,omitempty"`
	PerPage *PerPage `form:"per_page,omitempty" json:"per_page,omitempty"`
}

// CreateApplicationJSONRequestBody defines body for CreateApplication for application/json ContentType.
type CreateApplicationJSONRequestBody = ApplicationCreate

// PatchApplicationJSONRequestBody defines body for PatchApplication for application/json ContentType.
type PatchApplicationJSONRequestBody = ApplicationPatch

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// PatchLetterJSONRequestBody defines body for PatchLetter for application/json ContentType.
type PatchLetterJSONRequestBody = LetterPatch

// PatchMeJSONRequestBody defines body for PatchMe for application/json ContentType.
type PatchMeJSONRequestBody = PatchMeRequest

// ConnectGithubJSONRequestBody defines body for ConnectGithub for application/json ContentType.
type ConnectGithubJSONRequestBody = GithubConnectRequest

// CreatePortfolioItemJSONRequestBody defines body for CreatePortfolioItem for application/json ContentType.
type CreatePortfolioItemJSONRequestBody = PortfolioItemCreate

// PatchPortfolioItemJSONRequestBody defines body for PatchPortfolioItem for application/json ContentType.
type PatchPortfolioItemJSONRequestBody = PortfolioItemPatch

// UploadResumeMultipartRequestBody defines body for UploadResume for multipart/form-data ContentType.
type UploadResumeMultipartRequestBody UploadResumeMultipartBody

// CreateLetterJSONRequestBody defines body for CreateLetter for application/json ContentType.
type CreateLetterJSONRequestBody = LetterCreate
