{
  "вариант 1": {
    "url": "https://hh.ru/vacancy/137568898?query=Go+%D1%80%D0%B0%D0%B7%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%87%D0%B8%D0%BA&hhtmFrom=vacancy_search_list",
    "title": "Junior+ golang разработчик",
    "salary": { "amount": null, "currency": null, "note": "Уровень дохода не указан" },
    "experience": { "range": "1–3 года" },
    "employment": { "type": "Полная занятость" },
    "schedule": { "type": "5/2", "working_hours": 8 },
    "contract": { "type": "Трудовой договор" },
    "work_format": { "type": "на месте работодателя" },
    "views": { "currently_viewing": 11 },
    "actions": ["Откликнуться", "Связаться"]
  },
  "вариант 2": {
    "url": "https://hh.ru/vacancy/135976803?query=Go+%D1%80%D0%B0%D0%B7%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%87%D0%B8%D0%BA&hhtmFrom=vacancy_search_list",
    "title": "Go-разработчик, Карточка товара",
    "salary": { "amount": null, "currency": null, "note": "Уровень дохода не указан" },
    "experience": { "range": "1–3 года" },
    "employment": { "type": "Полная занятость" },
    "schedule": { "type": "5/2", "working_hours": 5 },
    "contract": { "type": "Трудовой договор" },
    "work_format": { "type": "на месте работодателя, удалённо или гибрид" },
    "views": { "currently_viewing": 12 },
    "actions": ["Откликнуться"]
  },
  "вариант 3": {
    "url": "https://hh.ru/vacancy/137902625?query=Go+%D1%80%D0%B0%D0%B7%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%87%D0%B8%D0%BA&hhtmFrom=vacancy_search_list",
    "title": "Middle Golang developer",
    "salary": { "amount": null, "currency": null, "note": "Уровень дохода не указан" },
    "experience": { "range": "3–6 лет" },
    "employment": { "type": "Полная занятость" },
    "schedule": { "type": "5/2", "working_hours": 8 },
    "contract": { "type": "Трудовой договор" },
    "work_format": { "type": "на месте работодателя" },
    "views": { "currently_viewing": 18 },
    "actions": ["Откликнуться"]
  },
  "вариант 4": {
    "url": "https://hh.ru/vacancy/138044465?query=python+%D1%80%D0%B0%D0%B7%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%87%D0%B8%D0%BA&hhtmFrom=vacancy_search_list",
    "title": "Python-разработчик - парсинг и сбор данных (Middle/Middle+)",
    "salary": { "amount": { "from": 180000, "to": 250000 }, "currency": "RUB", "period": "за месяц", "note": "на руки" },
    "payments": { "frequency": "два раза в месяц" },
    "experience": { "range": "не требуется" },
    "employment": { "type": "Полная занятость" },
    "schedule": { "type": "5/2 или свободный", "working_hours": 8 },
    "contract": { "type": "Трудовой договор" },
    "work_format": { "type": "на месте работодателя" },
    "views": { "currently_viewing": 13 },
    "actions": ["Откликнуться", "Связаться"]
  },
  "вариант 5": {
    "url": "https://hh.ru/vacancy/137892022?query=python+%D1%80%D0%B0%D0%B7%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%87%D0%B8%D0%BA&hhtmFrom=vacancy_search_list",
    "title": "Стажер RPA-разработчик",
    "salary": { "amount": { "from": 37500, "to": 75000 }, "currency": "RUB", "period": "за месяц", "note": "до вычета налогов" },
    "payments": { "frequency": "два раза в месяц" },
    "experience": { "range": "не требуется" },
    "employment": { "type": "Полная занятость" },
    "schedule": { "type": "5/2", "working_hours": "4 или 8" },
    "contract": { "type": "Трудовой договор" },
    "work_format": { "type": "на месте работодателя или гибрид" },
    "views": { "currently_viewing": 8 },
    "actions": ["Откликнуться"]
  },
  "вариант 6": {
    "url": "https://hh.ru/vacancy/136168308?query=python+%D1%80%D0%B0%D0%B7%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%87%D0%B8%D0%BA&hhtmFrom=vacancy_search_list",
    "title": "Инженер-программист",
    "salary": { "amount": null, "currency": null, "note": "Уровень дохода не указан" },
    "experience": { "range": "1–3 года" },
    "employment": { "type": "Полная занятость" },
    "schedule": { "type": "5/2", "working_hours": 8 },
    "contract": { "type": "Трудовой договор" },
    "work_format": { "type": "на месте работодателя или гибрид" },
    "views": { "currently_viewing": 6 },
    "actions": ["Откликнуться"]
  },
  "вариант 7": {
    "url": "https://hh.ru/vacancy/134717822?query=Frontend+%D1%80%D0%B0%D0%B7%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%87%D0%B8%D0%BA&hhtmFrom=vacancy_search_list",
    "title": "Стажер Frontend-разработчик",
    "salary": { "amount": null, "currency": null, "note": "Уровень дохода не указан" },
    "experience": { "range": "не требуется" },
    "employment": { "type": "Полная занятость", "subtype": "Стажировка" },
    "schedule": { "type": "5/2" },
    "work_format": { "type": "на месте работодателя" },
    "views": { "currently_viewing": 5 },
    "actions": ["Откликнуться"]
  },
  "вариант 8": {
    "url": "https://hh.ru/vacancy/137942876?query=Frontend+%D1%80%D0%B0%D0%B7%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%87%D0%B8%D0%BA&hhtmFrom=vacancy_search_list",
    "title": "Frontend-разработчик (стажёр)",
    "salary": { "amount": null, "currency": null, "note": "Уровень дохода не указан" },
    "experience": { "range": "не требуется" },
    "employment": { "type": "Полная занятость" },
    "schedule": { "type": "5/2", "working_hours": 8 },
    "work_format": { "type": "на месте работодателя" },
    "views": { "currently_viewing": 10 },
    "actions": ["Откликнуться", "Связаться"]
  },
  "вариант 9": {
    "url": "https://hh.ru/vacancy/135155890?query=Frontend+%D1%80%D0%B0%D0%B7%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%87%D0%B8%D0%BA&hhtmFrom=vacancy_search_list",
    "title": "Frontend разработчик (Vue.js) Middle/Senior",
    "salary": { "amount": null, "currency": null, "note": "Уровень дохода не указан" },
    "experience": { "range": "3–6 лет" },
    "employment": { "type": "Полная занятость" },
    "schedule": { "type": "5/2", "working_hours": 8 },
    "contract": { "type": "Трудовой договор" },
    "work_format": { "type": "на месте работодателя" },
    "views": { "currently_viewing": 7 },
    "actions": ["Откликнуться"]
  },
  "вариант 10": {
    "url": "https://hh.ru/vacancy/136133923?query=%D0%90%D0%BD%D0%B0%D0%BB%D0%B8%D0%B7+%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85&hhtmFrom=vacancy_search_list",
    "title": "Стажер в Управление \"Аналитика и отчетность продаж среднего и малого бизнеса\", ВТБ Юниор",
    "salary": { "amount": { "from": 81000, "to": 81000 }, "currency": "RUB", "period": "за месяц", "note": "до вычета налогов" },
    "payments": { "frequency": "два раза в месяц" },
    "experience": { "range": "не требуется" },
    "employment": { "type": "Полная занятость" },
    "schedule": { "type": "5/2", "working_hours": 8 },
    "work_format": { "type": "на месте работодателя" },
    "views": { "currently_viewing": 24 },
    "actions": ["Откликнуться"]
  },
  "вариант 11": {
    "url": "https://hh.ru/vacancy/137629935?query=%D0%90%D0%BD%D0%B0%D0%BB%D0%B8%D0%B7+%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85&hhtmFrom=vacancy_search_list",
    "title": "Аналитик данных (направление Enterprise продаж)",
    "salary": { "amount": null, "currency": null, "note": "Уровень дохода не указан" },
    "experience": { "range": "1–3 года" },
    "employment": { "type": "Полная занятость" },
    "schedule": { "type": "5/2", "working_hours": 8 },
    "contract": { "type": "Трудовой договор" },
    "work_format": { "type": "гибрид" },
    "views": { "currently_viewing": 8 },
    "actions": ["Откликнуться"]
  },
  "вариант 12": {
    "url": "https://hh.ru/vacancy/138016521?query=%D0%90%D0%BD%D0%B0%D0%BB%D0%B8%D0%B7+%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85&hhtmFrom=vacancy_search_list",
    "title": "Аналитик",
    "salary": { "amount": null, "currency": null, "note": "Уровень дохода не указан" },
    "experience": { "range": "1–3 года" },
    "employment": { "type": "Полная занятость" },
    "schedule": { "type": "5/2", "working_hours": 8 },
    "work_format": { "type": "на месте работодателя" },
    "views": { "currently_viewing": 12 },
    "actions": ["Откликнуться"]
  },
  "вариант 13": {
    "url": "https://hh.ru/vacancy/131449947?utm_medium=cpc_hh&utm_source=clickmehhru&utm_campaign=1227031&utm_local_campaign=1717795&utm_content=1275873
",
    "title": "Менеджер по продажам",
    "salary": { "amount": { "from": 140000, "to": null }, "currency": "RUB", "period": "за месяц", "note": "на руки" },
    "payments": { "frequency": "два раза в месяц" },
    "experience": { "range": "не требуется" },
    "employment": { "type": "Полная занятость" },
    "schedule": { "type": "5/2", "working_hours": 8 },
    "contract": { "type": "Трудовой договор" },
    "work_format": { "type": "на месте работодателя" },
    "views": { "currently_viewing": 8 },
    "actions": ["Откликнуться"]
  },
  "вариант 14": {
    "url": "https://hh.ru/vacancy/137109870?utm_medium=cpc_hh&utm_source=clickmehhru&utm_campaign=1336938&utm_local_campaign=1842486&utm_content=1386796",
    "title": "Диспетчер-логист",
    "salary": { "amount": { "from": 60000, "to": 80000 }, "currency": "RUB", "period": "за месяц", "note": "на руки" },
    "payments": { "frequency": "два раза в месяц" },
    "experience": { "range": "1–3 года" },
    "employment": { "type": "Полная занятость" },
    "schedule": { "type": "5/2", "working_hours": 8 },
    "contract": { "type": "Договор ГПХ с самозанятым, с ИП, с физлицом" },
    "work_format": { "type": "на месте работодателя" },
    "views": { "currently_viewing": 4 },
    "actions": ["Откликнуться", "Связаться"]
  },
  "вариант 15": {
    "url": "https://hh.ru/vacancy/137739000?query=%D0%B1%D1%83%D1%85%D0%B3%D0%B0%D0%BB%D1%82%D0%B5%D1%80&hhtmFrom=vacancy_search_list",
    "title": "Бухгалтер ВЭД ( метро Молодёжная)",
    "salary": { "amount": { "from": 130000, "to": 145000 }, "currency": "RUB", "period": "за месяц", "note": "на руки" },
    "experience": { "range": "3–6 лет" },
    "employment": { "type": "Полная занятость" },
    "schedule": { "type": "5/2", "working_hours": 8 },
    "work_format": { "type": "на месте работодателя" },
    "views": { "currently_viewing": 9 },
    "actions": ["Откликнуться", "Связаться"]
  }
}