/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Проверка, что сервер жив */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Регистрация
         * @description Создаёт пользователя и пустой профиль в одной транзакции, сразу выдаёт токен.
         *     Почта приводится к нижнему регистру. Пароль — от 8 символов, имя — не пустое.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Вход, в ответ — токен доступа
         * @description Токен действует 24 часа, продления нет. При неверной почте и при неверном пароле
         *     ответ одинаковый — по нему нельзя узнать, зарегистрирован ли человек.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Свой профиль
         * @description Клиентская часть опрашивает этот адрес раз в 5 секунд, пока `profile.resume_status = "processing"`.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Изменить желаемую должность, город, зарплату, тон писем
         * @description Меняются только переданные поля. Непереданное поле остаётся прежним.
         *     Стереть значение (сделать `null`) через этот адрес нельзя.
         */
        patch: operations["patchMe"];
        trace?: never;
    };
    "/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Поиск по справочнику навыков
         * @description Для подсказок при вводе навыков. Ищет по названию и синонимам, без учёта регистра.
         */
        get: operations["searchSkills"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Загрузить файл резюме
         * @description Файл сохраняется сразу, разбор ставится в очередь. Ход разбора — в `GET /me`,
         *     поле `profile.resume_status`. Новый файл заменяет старый.
         */
        post: operations["uploadResume"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/github": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Подключить профиль GitHub по имени пользователя
         * @description Загружает открытые репозитории как проекты портфолио. Повторный вызов обновляет их.
         */
        post: operations["connectGithub"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список проектов в портфолио */
        get: operations["listPortfolioItems"];
        put?: never;
        /** Добавить проект вручную */
        post: operations["createPortfolioItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Удалить проект */
        delete: operations["deletePortfolioItem"];
        options?: never;
        head?: never;
        /**
         * Изменить проект
         * @description Меняются только переданные поля.
         */
        patch: operations["patchPortfolioItem"];
        trace?: never;
    };
    "/vacancies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Общий поиск по вакансиям с фильтрами
         * @description Фильтр `salary_from` не отсекает вакансии без зарплаты: они идут ниже остальных.
         *     Дубли из разных источников показываются один раз.
         */
        get: operations["listVacancies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vacancies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Одна вакансия */
        get: operations["getVacancy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Персональная лента с оценкой и её разбором
         * @description Если профиль ещё не обработан или сервис моделей недоступен, лента строится
         *     по навыкам и фильтрам без смысловой близости, и `simplified = true`.
         *     Тогда `parts.similarity = null`.
         */
        get: operations["getFeed"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vacancies/{id}/letters": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Составить черновик письма к вакансии
         * @description Синхронный запрос, ответ — до 30 секунд. Если отклика на вакансию ещё нет,
         *     он создаётся в статусе `draft`. Фрагменты, которых нет в портфолио,
         *     перечислены в `unverified` (позиции в символах, `end` не включается).
         *     Письмо никогда не отправляется само.
         */
        post: operations["createLetter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/letters/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Письмо (последняя версия) */
        get: operations["getLetter"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Сохранить правки
         * @description Создаёт новую версию. `version` — номер версии, которую правил человек:
         *     если с тех пор появилась более новая, ответ 409 `version_conflict`.
         */
        patch: operations["patchLetter"];
        trace?: never;
    };
    "/letters/{id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Все версии письма, новые первыми */
        get: operations["listLetterVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Мои отклики */
        get: operations["listApplications"];
        put?: never;
        /** Создать отклик */
        post: operations["createApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Сменить статус отклика */
        patch: operations["patchApplication"];
        trace?: never;
    };
    "/admin/collection-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Журнал прогонов сбора (только администратор) */
        get: operations["listCollectionRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/data-quality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Показатели качества данных (только администратор) */
        get: operations["getDataQuality"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                /** @description Машинный код, по нему клиентская часть решает, что делать */
                code: string;
                /** @description Текст для человека, показывается как есть */
                message: string;
            };
        };
        Health: {
            /** @enum {string} */
            status: "ok" | "unavailable";
        };
        /** @enum {string} */
        Grade: "junior" | "middle" | "senior";
        /** @enum {string} */
        WorkFormat: "office" | "remote" | "hybrid";
        /** @enum {string} */
        Tone: "formal" | "neutral" | "friendly";
        /** @enum {string} */
        ResumeStatus: "none" | "processing" | "ready" | "failed";
        Skill: {
            /** Format: int64 */
            id: number;
            name: string;
        };
        RegisterRequest: {
            /** @description Почта, регистр не важен */
            email: string;
            password: string;
            full_name: string;
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        User: {
            /** Format: int64 */
            id: number;
            email: string;
            full_name: string;
            is_admin: boolean;
        };
        TokenResponse: {
            access_token: string;
            /** @enum {string} */
            token_type: "Bearer";
            /** Format: date-time */
            expires_at: string;
            user: components["schemas"]["User"];
        };
        Profile: {
            target_title: string | null;
            /** @enum {string|null} */
            target_grade: "junior" | "middle" | "senior" | null;
            cities: string[];
            work_formats: components["schemas"]["WorkFormat"][];
            salary_from: number | null;
            tone: components["schemas"]["Tone"];
            resume_status: components["schemas"]["ResumeStatus"];
            skills: components["schemas"]["Skill"][];
        };
        Me: {
            /** Format: int64 */
            id: number;
            email: string;
            full_name: string;
            is_admin: boolean;
            profile: components["schemas"]["Profile"];
        };
        /** @description Все поля необязательны; меняются только переданные. */
        PatchMeRequest: {
            full_name?: string;
            target_title?: string;
            target_grade?: components["schemas"]["Grade"];
            cities?: string[];
            work_formats?: components["schemas"]["WorkFormat"][];
            salary_from?: number;
            tone?: components["schemas"]["Tone"];
            /** @description Полный список навыков профиля (заменяет прежний) */
            skill_ids?: number[];
        };
        ResumeUploadResponse: {
            resume_status: components["schemas"]["ResumeStatus"];
        };
        GithubConnectRequest: {
            username: string;
        };
        PortfolioItem: {
            /** Format: int64 */
            id: number;
            title: string;
            summary: string;
            url: string | null;
            /** @enum {string} */
            source: "manual" | "github" | "resume";
            skills: components["schemas"]["Skill"][];
            /** Format: date-time */
            created_at: string;
        };
        PortfolioItemList: {
            items: components["schemas"]["PortfolioItem"][];
        };
        PortfolioItemCreate: {
            title: string;
            summary: string;
            url?: string;
            skill_ids?: number[];
        };
        PortfolioItemPatch: {
            title?: string;
            summary?: string;
            url?: string;
            skill_ids?: number[];
        };
        Vacancy: {
            /** Format: int64 */
            id: number;
            title: string;
            company: string;
            city: string | null;
            /** @enum {string|null} */
            grade: "junior" | "middle" | "senior" | null;
            /** @enum {string|null} */
            work_format: "office" | "remote" | "hybrid" | null;
            /** @description `null` — зарплата не указана. Никогда не `0` и никогда не угадывается */
            salary_from: number | null;
            salary_to: number | null;
            /** @description Код ISO 4217: RUB, USD, EUR */
            currency: string | null;
            skills: components["schemas"]["Skill"][];
            /** @description Источник основной копии: headhunter, superjob, ... */
            source: string;
            /** @description Ссылка на вакансию у источника */
            url: string;
            /** Format: date-time */
            published_at: string;
        };
        VacancyDetails: components["schemas"]["Vacancy"] & {
            description: string;
            /** @description Та же вакансия у других источников (склеенные дубли) */
            also_on: components["schemas"]["VacancyCopy"][];
        };
        VacancyCopy: {
            source: string;
            url: string;
        };
        VacancyPage: {
            items: components["schemas"]["Vacancy"][];
            total: number;
        };
        /** @description Четыре части формулы оценки, каждая от 0 до 1 */
        ScoreParts: {
            /**
             * Format: double
             * @description Смысловая близость; `null` в упрощённой ленте
             */
            similarity: number | null;
            /**
             * Format: double
             * @description Покрытие навыков
             */
            skills: number;
            /**
             * Format: double
             * @description Совпадение уровня
             */
            grade: number;
            /**
             * Format: double
             * @description Свежесть вакансии
             */
            freshness: number;
        };
        ScoreExplanation: {
            matched_skills: string[];
            missing_skills: string[];
            /**
             * @description Уровень вакансии относительно желаемого
             * @enum {string}
             */
            grade_fit: "match" | "lower" | "higher" | "unknown";
            parts: components["schemas"]["ScoreParts"];
        };
        FeedItem: {
            vacancy: components["schemas"]["Vacancy"];
            /** Format: double */
            score: number;
            explanation: components["schemas"]["ScoreExplanation"];
        };
        FeedResponse: {
            items: components["schemas"]["FeedItem"][];
            total: number;
            /** @description `true` — подбор упрощён (без смысловой близости), клиентская часть показывает пометку */
            simplified: boolean;
        };
        TextFragment: {
            /** @description Позиция первого символа (в символах, не байтах) */
            start: number;
            /** @description Позиция после последнего символа */
            end: number;
            text: string;
        };
        LetterCreate: {
            /** @description Если не задан — тон из профиля */
            tone?: components["schemas"]["Tone"];
        };
        Letter: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            application_id: number;
            /** Format: int64 */
            vacancy_id: number;
            content: string;
            version: number;
            /** @description Фрагменты, которых нет в портфолио — подсвечиваются в редакторе */
            unverified: components["schemas"]["TextFragment"][];
            /** Format: date-time */
            updated_at: string;
        };
        LetterPatch: {
            content: string;
            /** @description Версия, которую правил человек */
            version: number;
        };
        LetterVersion: {
            version: number;
            content: string;
            /** @enum {string} */
            author: "model" | "user";
            /** Format: date-time */
            created_at: string;
        };
        LetterVersionList: {
            items: components["schemas"]["LetterVersion"][];
        };
        /** @enum {string} */
        ApplicationStatus: "draft" | "sent" | "interview" | "offer" | "rejected";
        Application: {
            /** Format: int64 */
            id: number;
            vacancy: components["schemas"]["Vacancy"];
            status: components["schemas"]["ApplicationStatus"];
            /** Format: int64 */
            letter_id: number | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ApplicationPage: {
            items: components["schemas"]["Application"][];
            total: number;
        };
        ApplicationCreate: {
            /** Format: int64 */
            vacancy_id: number;
        };
        ApplicationPatch: {
            status: components["schemas"]["ApplicationStatus"];
        };
        CollectionRun: {
            /** Format: int64 */
            id: number;
            source: string;
            /** @enum {string} */
            status: "running" | "success" | "partial" | "failed";
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            finished_at: string | null;
            fetched: number;
            created: number;
            updated: number;
            errors: number;
            error_message: string | null;
        };
        CollectionRunPage: {
            items: components["schemas"]["CollectionRun"][];
            total: number;
        };
        DataQuality: {
            total_vacancies: number;
            /**
             * Format: double
             * @description Доля вакансий с указанной зарплатой
             */
            salary_share: number;
            /**
             * Format: double
             * @description Доля вакансий с распознанными навыками
             */
            skills_share: number;
            /**
             * Format: double
             * @description Доля склеенных дублей
             */
            duplicates_share: number;
            by_source: components["schemas"]["SourceQuality"][];
        };
        SourceQuality: {
            source: string;
            vacancies: number;
            /** Format: date-time */
            last_success_at: string | null;
        };
    };
    responses: {
        /** @description Запрос составлен неверно (код `validation_error` или `invalid_json`) */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "validation_error",
                 *         "message": "Пароль должен быть не короче 8 символов"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Нет токена, он просрочен или подделан — нужно войти заново (код `unauthorized`) */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "unauthorized",
                 *         "message": "Нужно войти"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Адрес только для администратора (код `forbidden`) */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "forbidden",
                 *         "message": "Недостаточно прав"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Ресурса нет или он чужой — ответ одинаковый (код `not_found`) */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "not_found",
                 *         "message": "Не найдено"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Внешний сервис временно недоступен (код `service_unavailable`) */
        Unavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "service_unavailable",
                 *         "message": "Сервис временно недоступен, попробуйте позже"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        Id: number;
        /** @description Номер страницы, с 1 */
        Page: number;
        PerPage: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Сервер и база доступны */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok"
                     *     }
                     */
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description База данных недоступна */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "unavailable"
                     *     }
                     */
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "email": "ivan@mail.ru",
                 *       "password": "s3cret-pass",
                 *       "full_name": "Иван Петров"
                 *     }
                 */
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Пользователь создан */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.stub.stub",
                     *       "token_type": "Bearer",
                     *       "expires_at": "2026-10-12T12:00:00Z",
                     *       "user": {
                     *         "id": 42,
                     *         "email": "ivan@mail.ru",
                     *         "full_name": "Иван Петров",
                     *         "is_admin": false
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            /** @description Почта уже зарегистрирована (код `email_taken`) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "email_taken",
                     *         "message": "Эта почта уже зарегистрирована"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "email": "ivan@mail.ru",
                 *       "password": "s3cret-pass"
                 *     }
                 */
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Вход выполнен */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.stub.stub",
                     *       "token_type": "Bearer",
                     *       "expires_at": "2026-10-12T12:00:00Z",
                     *       "user": {
                     *         "id": 42,
                     *         "email": "ivan@mail.ru",
                     *         "full_name": "Иван Петров",
                     *         "is_admin": false
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            /** @description Неверная почта или пароль (код `invalid_credentials`) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "invalid_credentials",
                     *         "message": "Неверная почта или пароль"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Пользователь и его профиль */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": 42,
                     *       "email": "ivan@mail.ru",
                     *       "full_name": "Иван Петров",
                     *       "is_admin": false,
                     *       "profile": {
                     *         "target_title": "Разработчик на Go",
                     *         "target_grade": "junior",
                     *         "cities": [
                     *           "Москва"
                     *         ],
                     *         "work_formats": [
                     *           "remote",
                     *           "hybrid"
                     *         ],
                     *         "salary_from": 120000,
                     *         "tone": "neutral",
                     *         "resume_status": "none",
                     *         "skills": [
                     *           {
                     *             "id": 12,
                     *             "name": "Go"
                     *           },
                     *           {
                     *             "id": 31,
                     *             "name": "PostgreSQL"
                     *           }
                     *         ]
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    patchMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "salary_from": 150000,
                 *       "cities": [
                 *         "Москва",
                 *         "Санкт-Петербург"
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["PatchMeRequest"];
            };
        };
        responses: {
            /** @description Профиль после изменения */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": 42,
                     *       "email": "ivan@mail.ru",
                     *       "full_name": "Иван Петров",
                     *       "is_admin": false,
                     *       "profile": {
                     *         "target_title": "Разработчик на Go",
                     *         "target_grade": "junior",
                     *         "cities": [
                     *           "Москва"
                     *         ],
                     *         "work_formats": [
                     *           "remote",
                     *           "hybrid"
                     *         ],
                     *         "salary_from": 120000,
                     *         "tone": "neutral",
                     *         "resume_status": "none",
                     *         "skills": [
                     *           {
                     *             "id": 12,
                     *             "name": "Go"
                     *           },
                     *           {
                     *             "id": 31,
                     *             "name": "PostgreSQL"
                     *           }
                     *         ]
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["Me"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
        };
    };
    searchSkills: {
        parameters: {
            query: {
                /** @description Начало названия навыка, от 1 символа */
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Найденные навыки, самые популярные первыми */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "id": 12,
                     *         "name": "Python"
                     *       },
                     *       {
                     *         "id": 57,
                     *         "name": "PyTorch"
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["Skill"][];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
        };
    };
    uploadResume: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description PDF или DOCX, не больше 10 МБ
                     */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Файл принят, разбор поставлен в очередь */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "resume_status": "processing"
                     *     }
                     */
                    "application/json": components["schemas"]["ResumeUploadResponse"];
                };
            };
            /** @description Не тот формат файла (код `unsupported_file`) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "unsupported_file",
                     *         "message": "Нужен файл PDF или DOCX"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Файл больше 10 МБ (код `file_too_large`) */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "file_too_large",
                     *         "message": "Файл больше 10 МБ"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    connectGithub: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "username": "ivan-petrov"
                 *     }
                 */
                "application/json": components["schemas"]["GithubConnectRequest"];
            };
        };
        responses: {
            /** @description Проекты загружены */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "items": [
                     *         {
                     *           "id": 7,
                     *           "title": "telegram-bot",
                     *           "summary": "Бот для заказа пиццы на Go",
                     *           "url": "https://github.com/ivan-petrov/telegram-bot",
                     *           "source": "github",
                     *           "skills": [
                     *             {
                     *               "id": 12,
                     *               "name": "Go"
                     *             }
                     *           ],
                     *           "created_at": "2026-10-05T10:00:00Z"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["PortfolioItemList"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            /** @description Нет такого пользователя GitHub (код `github_user_not_found`) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "github_user_not_found",
                     *         "message": "Пользователь GitHub не найден"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
            503: components["responses"]["Unavailable"];
        };
    };
    listPortfolioItems: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Все проекты пользователя, новые первыми */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "items": [
                     *         {
                     *           "id": 7,
                     *           "title": "Агрегатор вакансий",
                     *           "summary": "Сервер на Go, PostgreSQL, Docker",
                     *           "url": null,
                     *           "source": "manual",
                     *           "skills": [
                     *             {
                     *               "id": 12,
                     *               "name": "Go"
                     *             },
                     *             {
                     *               "id": 31,
                     *               "name": "PostgreSQL"
                     *             }
                     *           ],
                     *           "created_at": "2026-10-05T10:00:00Z"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["PortfolioItemList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createPortfolioItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "title": "Агрегатор вакансий",
                 *       "summary": "Сервер на Go, PostgreSQL, Docker",
                 *       "skill_ids": [
                 *         12,
                 *         31
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["PortfolioItemCreate"];
            };
        };
        responses: {
            /** @description Проект создан */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": 7,
                     *       "title": "Агрегатор вакансий",
                     *       "summary": "Сервер на Go, PostgreSQL, Docker",
                     *       "url": null,
                     *       "source": "manual",
                     *       "skills": [
                     *         {
                     *           "id": 12,
                     *           "name": "Go"
                     *         },
                     *         {
                     *           "id": 31,
                     *           "name": "PostgreSQL"
                     *         }
                     *       ],
                     *       "created_at": "2026-10-05T10:00:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["PortfolioItem"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
        };
    };
    deletePortfolioItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Проект удалён */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    patchPortfolioItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "summary": "Сервер на Go, PostgreSQL, pgvector"
                 *     }
                 */
                "application/json": components["schemas"]["PortfolioItemPatch"];
            };
        };
        responses: {
            /** @description Проект после изменения */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": 7,
                     *       "title": "Агрегатор вакансий",
                     *       "summary": "Сервер на Go, PostgreSQL, Docker",
                     *       "url": null,
                     *       "source": "manual",
                     *       "skills": [
                     *         {
                     *           "id": 12,
                     *           "name": "Go"
                     *         },
                     *         {
                     *           "id": 31,
                     *           "name": "PostgreSQL"
                     *         }
                     *       ],
                     *       "created_at": "2026-10-05T10:00:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["PortfolioItem"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listVacancies: {
        parameters: {
            query?: {
                /** @description Слова из названия или описания */
                q?: string;
                city?: string;
                grade?: components["schemas"]["Grade"];
                work_format?: components["schemas"]["WorkFormat"];
                salary_from?: number;
                /** @description Номера навыков; вакансия должна требовать все перечисленные */
                skill_id?: number[];
                /** @description Номер страницы, с 1 */
                page?: components["parameters"]["Page"];
                per_page?: components["parameters"]["PerPage"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Страница вакансий */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "items": [
                     *         {
                     *           "id": 4821,
                     *           "title": "Разработчик на Go",
                     *           "company": "Ромашка",
                     *           "city": "Москва",
                     *           "grade": "junior",
                     *           "work_format": "hybrid",
                     *           "salary_from": 180000,
                     *           "salary_to": null,
                     *           "currency": "RUB",
                     *           "skills": [
                     *             {
                     *               "id": 12,
                     *               "name": "Go"
                     *             },
                     *             {
                     *               "id": 31,
                     *               "name": "PostgreSQL"
                     *             },
                     *             {
                     *               "id": 40,
                     *               "name": "Docker"
                     *             }
                     *           ],
                     *           "source": "headhunter",
                     *           "url": "https://hh.ru/vacancy/4821",
                     *           "published_at": "2026-10-03T09:15:00Z"
                     *         }
                     *       ],
                     *       "total": 1
                     *     }
                     */
                    "application/json": components["schemas"]["VacancyPage"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getVacancy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Вакансия с полным описанием */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": 4821,
                     *       "title": "Разработчик на Go",
                     *       "company": "Ромашка",
                     *       "city": "Москва",
                     *       "grade": "junior",
                     *       "work_format": "hybrid",
                     *       "salary_from": 180000,
                     *       "salary_to": null,
                     *       "currency": "RUB",
                     *       "skills": [
                     *         {
                     *           "id": 12,
                     *           "name": "Go"
                     *         },
                     *         {
                     *           "id": 31,
                     *           "name": "PostgreSQL"
                     *         },
                     *         {
                     *           "id": 40,
                     *           "name": "Docker"
                     *         }
                     *       ],
                     *       "source": "headhunter",
                     *       "url": "https://hh.ru/vacancy/4821",
                     *       "published_at": "2026-10-03T09:15:00Z",
                     *       "description": "Ищем разработчика в команду платёжного шлюза...",
                     *       "also_on": [
                     *         {
                     *           "source": "superjob",
                     *           "url": "https://superjob.ru/vakansii/4821.html"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["VacancyDetails"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getFeed: {
        parameters: {
            query?: {
                /** @description Если не задан — города из профиля */
                city?: string;
                /** @description Номер страницы, с 1 */
                page?: components["parameters"]["Page"];
                per_page?: components["parameters"]["PerPage"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Страница ленты */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "items": [
                     *         {
                     *           "vacancy": {
                     *             "id": 4821,
                     *             "title": "Разработчик на Go",
                     *             "company": "Ромашка",
                     *             "city": "Москва",
                     *             "grade": "junior",
                     *             "work_format": "hybrid",
                     *             "salary_from": 180000,
                     *             "salary_to": null,
                     *             "currency": "RUB",
                     *             "skills": [
                     *               {
                     *                 "id": 12,
                     *                 "name": "Go"
                     *               },
                     *               {
                     *                 "id": 31,
                     *                 "name": "PostgreSQL"
                     *               },
                     *               {
                     *                 "id": 40,
                     *                 "name": "Docker"
                     *               }
                     *             ],
                     *             "source": "headhunter",
                     *             "url": "https://hh.ru/vacancy/4821",
                     *             "published_at": "2026-10-03T09:15:00Z"
                     *           },
                     *           "score": 0.83,
                     *           "explanation": {
                     *             "matched_skills": [
                     *               "Go",
                     *               "PostgreSQL",
                     *               "Docker"
                     *             ],
                     *             "missing_skills": [
                     *               "Kubernetes"
                     *             ],
                     *             "grade_fit": "match",
                     *             "parts": {
                     *               "similarity": 0.79,
                     *               "skills": 0.75,
                     *               "grade": 1,
                     *               "freshness": 0.95
                     *             }
                     *           }
                     *         }
                     *       ],
                     *       "total": 20,
                     *       "simplified": false
                     *     }
                     */
                    "application/json": components["schemas"]["FeedResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
        };
    };
    createLetter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                /**
                 * @example {
                 *       "tone": "friendly"
                 *     }
                 */
                "application/json": components["schemas"]["LetterCreate"];
            };
        };
        responses: {
            /** @description Черновик составлен */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": 15,
                     *       "application_id": 9,
                     *       "vacancy_id": 4821,
                     *       "content": "Здравствуйте! Меня заинтересовала вакансия разработчика на Go. Я работал с Kubernetes...",
                     *       "version": 1,
                     *       "unverified": [
                     *         {
                     *           "start": 120,
                     *           "end": 130,
                     *           "text": "Kubernetes"
                     *         }
                     *       ],
                     *       "updated_at": "2026-10-05T10:00:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["Letter"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /**
             * @description Языковая модель недоступна (`letter_service_unavailable`) или после двух попыток
             *     не удалось составить письмо без выдуманных фактов (`letter_generation_failed`)
             */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "letter_service_unavailable",
                     *         "message": "Составление писем временно недоступно"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getLetter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Письмо */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": 15,
                     *       "application_id": 9,
                     *       "vacancy_id": 4821,
                     *       "content": "Здравствуйте! Меня заинтересовала вакансия разработчика на Go. Я работал с Kubernetes...",
                     *       "version": 1,
                     *       "unverified": [
                     *         {
                     *           "start": 120,
                     *           "end": 130,
                     *           "text": "Kubernetes"
                     *         }
                     *       ],
                     *       "updated_at": "2026-10-05T10:00:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["Letter"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    patchLetter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "content": "Здравствуйте! Меня заинтересовала вакансия...",
                 *       "version": 1
                 *     }
                 */
                "application/json": components["schemas"]["LetterPatch"];
            };
        };
        responses: {
            /** @description Сохранённая версия */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": 15,
                     *       "application_id": 9,
                     *       "vacancy_id": 4821,
                     *       "content": "Здравствуйте! Меня заинтересовала вакансия...",
                     *       "version": 2,
                     *       "unverified": [],
                     *       "updated_at": "2026-10-05T10:00:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["Letter"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description Письмо уже изменено в другом окне (код `version_conflict`) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "version_conflict",
                     *         "message": "Письмо изменилось, обновите страницу"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listLetterVersions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Версии */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "items": [
                     *         {
                     *           "version": 2,
                     *           "content": "Здравствуйте! Меня заинтересовала вакансия...",
                     *           "author": "user",
                     *           "created_at": "2026-10-05T10:07:00Z"
                     *         },
                     *         {
                     *           "version": 1,
                     *           "content": "Здравствуйте! Меня заинтересовала вакансия разработчика на Go...",
                     *           "author": "model",
                     *           "created_at": "2026-10-05T10:00:00Z"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["LetterVersionList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listApplications: {
        parameters: {
            query?: {
                status?: components["schemas"]["ApplicationStatus"];
                /** @description Номер страницы, с 1 */
                page?: components["parameters"]["Page"];
                per_page?: components["parameters"]["PerPage"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Страница откликов, последние изменённые первыми */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "items": [
                     *         {
                     *           "id": 9,
                     *           "vacancy": {
                     *             "id": 4821,
                     *             "title": "Разработчик на Go",
                     *             "company": "Ромашка",
                     *             "city": "Москва",
                     *             "grade": "junior",
                     *             "work_format": "hybrid",
                     *             "salary_from": 180000,
                     *             "salary_to": null,
                     *             "currency": "RUB",
                     *             "skills": [
                     *               {
                     *                 "id": 12,
                     *                 "name": "Go"
                     *               },
                     *               {
                     *                 "id": 31,
                     *                 "name": "PostgreSQL"
                     *               },
                     *               {
                     *                 "id": 40,
                     *                 "name": "Docker"
                     *               }
                     *             ],
                     *             "source": "headhunter",
                     *             "url": "https://hh.ru/vacancy/4821",
                     *             "published_at": "2026-10-03T09:15:00Z"
                     *           },
                     *           "status": "draft",
                     *           "letter_id": 15,
                     *           "created_at": "2026-10-05T10:00:00Z",
                     *           "updated_at": "2026-10-05T10:00:00Z"
                     *         }
                     *       ],
                     *       "total": 1
                     *     }
                     */
                    "application/json": components["schemas"]["ApplicationPage"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
        };
    };
    createApplication: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "vacancy_id": 4821
                 *     }
                 */
                "application/json": components["schemas"]["ApplicationCreate"];
            };
        };
        responses: {
            /** @description Отклик создан */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": 9,
                     *       "vacancy": {
                     *         "id": 4821,
                     *         "title": "Разработчик на Go",
                     *         "company": "Ромашка",
                     *         "city": "Москва",
                     *         "grade": "junior",
                     *         "work_format": "hybrid",
                     *         "salary_from": 180000,
                     *         "salary_to": null,
                     *         "currency": "RUB",
                     *         "skills": [
                     *           {
                     *             "id": 12,
                     *             "name": "Go"
                     *           },
                     *           {
                     *             "id": 31,
                     *             "name": "PostgreSQL"
                     *           },
                     *           {
                     *             "id": 40,
                     *             "name": "Docker"
                     *           }
                     *         ],
                     *         "source": "headhunter",
                     *         "url": "https://hh.ru/vacancy/4821",
                     *         "published_at": "2026-10-03T09:15:00Z"
                     *       },
                     *       "status": "draft",
                     *       "letter_id": null,
                     *       "created_at": "2026-10-05T10:00:00Z",
                     *       "updated_at": "2026-10-05T10:00:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["Application"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description Отклик на эту вакансию уже есть (код `application_exists`) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "application_exists",
                     *         "message": "Отклик на эту вакансию уже создан"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    patchApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "status": "sent"
                 *     }
                 */
                "application/json": components["schemas"]["ApplicationPatch"];
            };
        };
        responses: {
            /** @description Отклик после изменения */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": 9,
                     *       "vacancy": {
                     *         "id": 4821,
                     *         "title": "Разработчик на Go",
                     *         "company": "Ромашка",
                     *         "city": "Москва",
                     *         "grade": "junior",
                     *         "work_format": "hybrid",
                     *         "salary_from": 180000,
                     *         "salary_to": null,
                     *         "currency": "RUB",
                     *         "skills": [
                     *           {
                     *             "id": 12,
                     *             "name": "Go"
                     *           },
                     *           {
                     *             "id": 31,
                     *             "name": "PostgreSQL"
                     *           },
                     *           {
                     *             "id": 40,
                     *             "name": "Docker"
                     *           }
                     *         ],
                     *         "source": "headhunter",
                     *         "url": "https://hh.ru/vacancy/4821",
                     *         "published_at": "2026-10-03T09:15:00Z"
                     *       },
                     *       "status": "sent",
                     *       "letter_id": 15,
                     *       "created_at": "2026-10-05T10:00:00Z",
                     *       "updated_at": "2026-10-06T08:30:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["Application"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listCollectionRuns: {
        parameters: {
            query?: {
                source?: string;
                /** @description Номер страницы, с 1 */
                page?: components["parameters"]["Page"];
                per_page?: components["parameters"]["PerPage"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Прогоны, новые первыми */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "items": [
                     *         {
                     *           "id": 301,
                     *           "source": "headhunter",
                     *           "status": "success",
                     *           "started_at": "2026-10-05T03:00:00Z",
                     *           "finished_at": "2026-10-05T03:04:12Z",
                     *           "fetched": 1200,
                     *           "created": 85,
                     *           "updated": 310,
                     *           "errors": 0,
                     *           "error_message": null
                     *         }
                     *       ],
                     *       "total": 1
                     *     }
                     */
                    "application/json": components["schemas"]["CollectionRunPage"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getDataQuality: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Показатели по всем вакансиям и по источникам */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "total_vacancies": 15230,
                     *       "salary_share": 0.62,
                     *       "skills_share": 0.91,
                     *       "duplicates_share": 0.18,
                     *       "by_source": [
                     *         {
                     *           "source": "headhunter",
                     *           "vacancies": 9800,
                     *           "last_success_at": "2026-10-05T03:04:12Z"
                     *         },
                     *         {
                     *           "source": "superjob",
                     *           "vacancies": 5430,
                     *           "last_success_at": null
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["DataQuality"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
}
